language: php
php:
  - 5.3
  - 5.6
  - 7.0
script:
  - ./vendor/bin/phpunit --configuration phpunit.xml

before_script:
  # Install Nette Tester
  - composer install --no-interaction --dev --prefer-source
